package foo

func f() error {
	try(1 + 1)
}
